// Generated by Structorizer 3.32-11 

using System;

/// <summary>
/// </summary>
public class Ejercicio04
{

	/// <param name="args"> array of command line arguments </param>
	public static void Main(string[] args)
	{

		// TODO: Check and accomplish variable declarations: 
		??? num;

		// TODO: You may have to modify input instructions, 
		//       possibly by enclosing Console.ReadLine() calls with 
		//       Parse methods according to the variable type, e.g.: 
		//          i = int.Parse(Console.ReadLine()); 

		Console.Write("Introduce un número"); , num = Console.ReadLine();
		if (num>15)
		{
			multiplicación==num*3;
			// En este caso multiplicacion  
			// nunca puede ser menor que 20 
			??? resultado = multiplicación+100;
		}
		else
		{
			multiplicación==num*5;
			if (multiplicación<20)
			{
				resultado = multiplicación+200;
			}
			else
			{
				resultado = multiplicación+100;
			}
		}
		Console.WriteLine(resultado);
	}

}