// Generated by Structorizer 3.32-11 

using System;

/// <summary>
/// </summary>
public class Ejercicio3
{

	/// <param name="args"> array of command line arguments </param>
	public static void Main(string[] args)
	{

		// TODO: Check and accomplish variable declarations: 
		// Añadir el valor de num a lo que tiene 
		//  hasta ahora el acumulador 
		int total;
		??? num;

		// TODO: You may have to modify input instructions, 
		//       possibly by enclosing Console.ReadLine() calls with 
		//       Parse methods according to the variable type, e.g.: 
		//          i = int.Parse(Console.ReadLine()); 

		// Inicializar el acumulador total 
		total = 0;
		// Repetir 3 veces 
		for (int vuelta = 1; vuelta <= 3; vuelta += (1))
		{
			// Leer numero para valorar 
			num = Console.ReadLine();
			if (num>25)
			{
				// Añadir el valor de num a lo que tiene 
				//  hasta ahora el acumulador 
				total = total + num;
			}
		}
		// Mostrar la totalizacion de los numeros que superaban 25 
		Console.WriteLine(total);
	}

}